### ISSUE TITLE
'aux' directory should be renamed

### ISSUE THREAD

**Issue by jrf-consulting** [multigraph/js-multigraph#76]
On windows systems the word `aux` is reserved for auxiliary devices and thus cannot be used as a directory name, making git automatically delete this directory and stage it for deletion on clone. There is no way to unstage it due to this restriction. While the following link listing forbidden directories in windows claims you can create a directory named `aux`, this feature has been removed in at least windows 8.1 http://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/

**Comment by embeepea** [comment]
This is a bug in Windows and/or git, not multigraph.
